#+TITLE: Introduction to SIR models in Python

* Introduction

This material is part of a one-day course in transmission modeling for
applied epidemiology that will be held on June 22, 2018 as part of the
[[http://icmb2018.bucea.edu.cn/index.htm][6th International Conference on Mathematical Biology]], in Beijing, PR
China.

This repository provides the code for the hands-on practical exercises
in the Python programming language.

* Requirements

To use the code provided you will require the Jupyter notebook and a
Python installation with the SciPy, NumPy, Matplotlib and ipywidgets
libraries, as well as all their dependencies.

The easiest way to obtain every requirement is to install the Anaconda
Distribution, which includes everything needed (plus a lot more):
https://www.anaconda.com/download

If you do not want to install anything in your computer, you can also
run the code online. This method will be slower and you will have to
copy and paste each instruction. To try it go to:
https://jupyter.org/try and click on "Try Jupyter with Python".

* Code

The code is provided as [[file:SIR_models.ipynb][one Jupyter notebook]].
