#+TITLE: Introduction to SIR models in Python

This material is part of a one-day course in transmission modeling for
applied epidemiology that will be held on June 22, 2018 as part of the
[[http://icmb2018.bucea.edu.cn/index.htm][6th International Conference on Mathematical Biology]], in Beijing, PR
China.

This repository contains the code for the hands-on practical exercises
in the Python programming language.

* Instructions

The code can be run from your browser visiting:

https://mybinder.org/v2/gh/alfaromurillo/sir_models_intro/master?filepath=SIR_models.ipynb

Alternatively, you could download the notebook (right click on this
[[https://github.com/alfaromurillo/sir_models_intro/blob/master/SIR_models.ipynb?raw=true][link]] and choose 'Save link as...') and run it in your computer if you
have the Jupyter Notebook and a Python installation with the SciPy,
Matplotlib and ipywidgets libraries. The easiest way to install the
Jupyter Notebook is to install the Anaconda Distribution, which
includes every dependence needed (plus a lot more):
https://www.anaconda.com/download. Follow the instructions there for
your appropriate operative system.
